<?php
namespace app\modules\auth\classes;
class Password
{
    public function ForgotPassword($data)
    {
        $params = array(
            array(":EmailID", $data["EmailID"])
        );

        $query = "SELECT * FROM users WHERE EmailID=:EmailID;";

        $user = DBController::sendData($query, $params);

        if ($user) {
            $password = rand(100000, 999999);


            $params = array(
                array(":Password", hash("sha256", substr($user["Username"], 0, 1) . $password)),
                array(":EmailID", $user["EmailID"]),
                array(":UserID", $user["UserID"])
            );

            $query = "UPDATE users SET Password=:Password WHERE EmailID=:EmailID AND UserID=:UserID;";

            $array = DBController::ExecuteSQL($query, $params);

            if ($array) {

                $body = '	<span class="im">
                            <p style="color:#333333;margin:10px 0;padding:0">Hi <strong>' . $user['Name'] . '</strong>,</p>
                            <p style="color:#333333;margin:10px 0;padding:0">You password has been resetted<br/>
                            and the following is your password for login into the Portal.</p>
                            <p style="color:#333333;margin:10px 0;padding:0">Email : ' . $data['EmailID'] . '</p>
                            <p style="color:#333333;margin:10px 0;padding:0">Password : ' . $password . '</p>
                        </span>
                        <p style="color:#333333;max-width:600px;margin:10px 0;padding:0 0 15px">
                            The link for the web portal is :<br>
                            <a style="color:#2c7cb0;font-size:20px" href="https://PrayagEdu.in/" target="_blank">Login</a>
                        </p>';

                $Subject = "PrayagEdu Forgot  Password";

                require_once("../app/misc/Email.php");
                if (Email::send($body, $user['EmailID'], $Subject)) {
                    return array("return_code" => true, "return_data" => "Please Check Your Mail for your autogenerated password.\n There may be a delay of few minutes before you recieve the mail.\nThank You");
                } else {
                    return array("return_code" => true, "return_data" => "Problem Sending mail\nThank You");
                }
            }
        }
        return array("return_code" => false, "return_data" =>  $data['EmailID'] . " is not yet registered");
    }

    public function ChangePassword($data)
    {
        $params = array(
            array(":UserID", $_SESSION["UserID"]),
			array(":Username", $_SESSION['Username']),
			array(":oldpassword", hash("sha256",substr($_SESSION['Username'],0,1).$data['oldpassword']))
        );

        $query = "SELECT * FROM users WHERE UserID=:UserID AND Username=:Username AND Password=:oldpassword;";

        $user = DBController::sendData($query, $params);

        if ($user) {
            $password = $data["newpassword"];


            $params = array(
                array(":Password", hash("sha256", substr($user["Username"], 0, 1) . $password)),
                array(":EmailID", $user["EmailID"]),
                array(":UserID", $user["UserID"])
            );

            $query = "UPDATE users SET Password=:Password WHERE EmailID=:EmailID AND UserID=:UserID;";

            $array = DBController::ExecuteSQL($query, $params);

            if ($array) {

                $body = '	<span class="im">
                            <p style="color:#333333;margin:10px 0;padding:0">Hi <strong>' . $user['Name'] . '</strong>,</p>
                            <p style="color:#333333;margin:10px 0;padding:0">You password has been resetted<br/>
                            and the following is your password for login into the Portal.</p>
                            <p style="color:#333333;margin:10px 0;padding:0">Email : ' . $user['EmailID'] . '</p>
                            <p style="color:#333333;margin:10px 0;padding:0">Password : ' . $password . '</p>
                        </span>
                        <p style="color:#333333;max-width:600px;margin:10px 0;padding:0 0 15px">
                            The link for the web portal is :<br>
                            <a style="color:#2c7cb0;font-size:20px" href="https://PrayagEdu.in/" target="_blank">Login</a>
                        </p>';

                $Subject = "PrayagEdu Reset  Password";

                require_once("../app/misc/Email.php");
                if (Email::send($body, $user['EmailID'], $Subject)) {
                    return array("return_code" => true, "return_data" => "Please Check Your Mail for your autogenerated password.\n There may be a delay of few minutes before you recieve the mail.\nThank You");
                } else {
                    return array("return_code" => true, "return_data" => "Problem Sending mail\nThank You");
                }
            }
        }
        return array("return_code" => false, "return_data" =>   " Credentials incorrect");
    }
}
