<?php
namespace app\modules\auth\classes;

use app\database\DBController;
use app\misc\Email;
use app\misc\SMS;
use app\modules\student\classes\Student;

class Signup
{
    function request($data)
    {
        $user = (new Users())->exists($data);
        $user = $user['return_data'];

        if ($user) {
            if ((isset($user["EmailID"]) && ($user["EmailID"]==$data["EmailID"])) && (isset($user["ContactNo"]) && ($user["EmailID"]==$data["EmailID"]))) {
                return array("return_code" => false, "return_data" =>  "EmailID and Contact No Already Exists!!");
            } elseif (isset($user["EmailID"]) && ($user["EmailID"]==$data["EmailID"])) {
                return array("return_code" => false, "return_data" =>  "EmailID Already Exists!!");
            } elseif (isset($user["ContactNo"]) && ($user["ContactNo"]==$data["ContactNo"])) {
                return array("return_code" => false, "return_data" =>  "Contact No Already Exists!!");
            }
        }

        //we do not need student
       /*
            $student = new Student();
            $student = $student->checkSignupStudent($data);

            if ($student['return_code'] && count($student['return_data'])==0 ) {
                return array("return_code" => false, "return_data" =>  "Student is already registered!!");
            }
            $student = $student['return_data'];
        */

        $password = rand(100000, 999999);

        if (!isset($data["UserType"])) {
            $data["UserType"] = 3;
        }

        $params = array(
            array(":Name", $data["Name"]),
            array(":Username", $data["Username"]),
            array(":Password", hash("sha256", substr($data["Username"], 0, 1) . $password)),
            array(":EmailID", $data["EmailID"]),
            array(":ContactNo", $data["ContactNo"]),
            array(":UserType", $data["UserType"]),
        );

        $query = "INSERT INTO Users(Name, Username, Password, EmailID, ContactNo, UserType) VALUES (:Name,:Username,:Password,:EmailID,:ContactNo,:UserType)";
        $array = DBController::ExecuteSQLID($query, $params);

        if ($array) {

			$body='<span class="im">
						<p style="color:#333333;margin:10px 0;padding:0">Hi <strong>' . $data['Name'] . '</strong>,</p>
						<p style="color:#333333;margin:10px 0;padding:0">You have successfully Registered with PrayagEdu<br/>
						and the following is your password for login into the Portal.</p>
						<p style="color:#333333;margin:10px 0;padding:0">Email : ' . $data['EmailID'] . '</p>
						<p style="color:#333333;margin:10px 0;padding:0">Password : ' . $password . '</p>
					</span>
					<p style="color:#333333;max-width:600px;margin:10px 0;padding:0 0 15px">
						The link for the web portal is :<br>
						<a style="color:#2c7cb0;font-size:20px" href="https://PrayagEdu.in/" target="_blank">Login</a>
					</p>';

			$Subject = "PrayagEdu Registration";
			$message ="Dear Participant,\n\n Your password of PrayagEdu portal is \n Password: ".$password ." \n\nFor login go to https://PrayagEdu.techz.in/";

            if (SMS::send('ITPLTZ', $message,  $data["ContactNo"]) || Email::send($body, $data['EmailID'], $Subject)) {
                return array("return_code" => true, "return_data" => "Please Check Your Mail for your autogenerated password.\n There may be a delay of few minutes before you recieve the mail.\nThank You");
            } else {
                return array("return_code" => true, "return_data" => "Problem Sending mail\nThank You");
            }
        }
    }
}